apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-manager-backend-deployment
  labels:
    app: expenses-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-manager-backend
  template:
    metadata:
      labels:
        app: expenses-manager-backend
    spec:
      containers:
        - name: expenses-manager-backend
          image: rahulshome/expenses-manager-backend:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: "0.25"
            limits:
              memory: 1024Mi
              cpu: "0.50"
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_TOPIC
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_CONSUMER_GROUP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-manager-ui-deployment
  labels:
    app: expenses-manager-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-manager-ui
  template:
    metadata:
      labels:
        app: expenses-manager-ui
    spec:
      containers:
        - name: expenses-manager-ui
          image: rahulshome/expenses-manager-ui:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: "0.25"
            limits:
              memory: 256Mi
              cpu: "0.50"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: expenses-manager-backend-service
spec:
  ports:
    - port: 80
  selector:
    app: expenses-manager-backend

---
apiVersion: v1
kind: Service
metadata:
  name: expenses-manager-ui-service
spec:
  ports:
    - port: 80
  selector:
    app: expenses-manager-ui
