apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYjovL21vbmdvZC0wLm1vbmdvZGItc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LG1vbmdvZC0xLm1vbmdvZGItc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LG1vbmdvZC0yLm1vbmdvZGItc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3
